sudo: false
dist: xenial
language: ruby
rvm:
  - 2.5.1
branches:
  only:
      - master
services:
  - mysql
install:
  - gem install bundler
  - bundle install
before_script:
  - cp config.yml.sample config.yml
  - RACK_ENV=test
  - rake db:create:all
  - rake db:schema:load
  - rake db:migrate