sudo: false
dist: xenial
language: ruby
rvm:
  - 2.6.3
branches:
  only:
      - master
addons:
  apt:
    packages:
      - libmagic-dev
      - libicu-dev
services:
  - mysql
install:
  - gem install bundler
  - bundle install
before_script:
  - cp config/settings/test.yml.sample config/settings/test.yml
  - RACK_ENV=test
  - rake db:create:all
  - rake db:schema:load
  - rake db:migrate
