source 'http://rubygems.org'
ruby '2.5.1'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mysql2'
gem 'activerecord'
gem 'activerecord-import'
gem 'rest-client'
gem 'sanitize'
gem 'htmlentities'
gem 'haml'
gem 'namae'
gem 'capitalize-names'
gem 'elasticsearch'
gem 'will_paginate'
gem 'chronic'
gem 'omniauth-orcid'
gem 'thin'
gem 'oauth2'
gem 'require_all'
gem 'rack-google-analytics'
gem 'nokogiri'
gem 'ruby-progressbar'
gem 'parallel'
gem 'dwc-archive'
gem 'redis'
gem 'sidekiq'
gem 'dwc_agent'
gem 'iso_country_codes'
gem 'neo4j'
gem 'colorize'

group :production do
end

group :test, :development do
  gem 'rake'
  gem 'rspec'
  gem 'byebug'
end