source 'http://rubygems.org'
ruby '2.6.3'

gem 'activerecord'
gem 'activerecord-import'
gem 'active_record_union'
gem 'biodiversity'
gem 'capitalize-names'
gem 'chronic'
gem 'colorize'
gem 'config'
gem 'dwc_agent'
gem 'dwc-archive'
gem 'elasticsearch'
gem 'datapackage'
gem 'haml'
gem 'htmlentities'
gem 'i18n'
gem 'iso_country_codes'
gem 'mysql2'
gem 'namae'
gem 'neo4j'
gem 'nokogiri'
gem 'oauth2'
gem 'omniauth-orcid'
gem 'oj'
gem 'pagy'
gem 'pluck_to_hash'
gem 'pony'
gem 'rack-contrib'
gem 'rack-google-analytics'
gem 'redis'
gem 'require_all'
gem 'rest-client'
gem 'rss'
gem 'ruby-filemagic'
gem 'ruby-progressbar'
gem 'rubysl-securerandom'
gem 'rubyzip'
gem 'sanitize'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-cacher'
gem 'sinatra-contrib'
gem 'sinatra-outputbuffer'
gem 'sinatra-flash'
gem 'sinatra-support'
gem 'sparql-client'
gem 'thin'
gem 'twitter'
gem 'wikidata-client'
gem 'xml-sitemap'

group :production do
end

group :test, :development do
  gem 'byebug'
  gem 'rake'
  gem 'rspec'
end
